openapi: 3.0.1
info:
  title: documentation-videos
  description: Cortex descriptor created automatically by eng-devprod
  x-cortex-tag: documentation-videos
  x-cortex-type: service
  x-cortex-owners:
  - name: cse
    type: group
    provider: OKTA
    description: Updated by eng-devprod

